networks:
  services:
    name: services
    external: true
  symfony-network:

services:
  php:
    build:
#      target: php
      context: .
      target: php-debug
    volumes:
      - ./:/srv/app
      - ./var:/srv/app/var:rw
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    env_file:
      - .env.local
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE:-debug}
    networks:
      - symfony-network
      - services

  caddy:
    build:
      target: caddy
      context: .
    volumes:
      - ./public:/srv/app/public:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - symfony-network
      - services
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.symfony.rule=Host(`symfony.localhost`)"
      - "traefik.http.routers.symfony.entrypoints=https"
      - "traefik.http.routers.symfony.tls=true"
      - "traefik.http.services.symfony.loadbalancer.server.port=80"
